name: anantla_pay
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  dartz: ^0.10.1
  dio: ^5.4.2+1
  dropdown_search: ^6.0.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^19.0.0
  flutter_qris: ^1.0.1+8
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mobile_scanner: ^6.0.7
  numpad_layout: ^0.0.3
  permission_handler: ^11.4.0
  pretty_dio_logger: ^1.3.1
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.8
  change_app_package_name: ^1.5.0
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/anantla_logo_black.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/anantla_logo_black.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/anantla_logo_black.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/anantla_logo_black.png"

flutter_gen:
  output: lib/src/core/utils/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/icons/navbar/
